lib/rasbet_web/router.ex
defmodule RasbetWeb.Router do
  use RasbetWeb, :router

  import RasbetWeb.UserAuth

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {RasbetWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
    plug(RasbetWeb.Plugs.SetLocale)

    # plug SetLocale, gettext: RasbetWeb.Gettext, default_locale: "pt"
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", RasbetWeb do
    pipe_through(:browser)

    live("/", GameLive.Index, :index)
    live("/promos", PromosLive.Index, :index)
  end

  # Other scopes may use custom stacks.
  # scope "/api", RasbetWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)

      live_dashboard("/dashboard", metrics: RasbetWeb.Telemetry)
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through(:browser)

      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end

  ## Authentication routes

  scope "/", RasbetWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])

    # get "/users/register", UserRegistrationController, :new
    live("/users/register", UserLive.Registration, :new)
    post("/users/register", UserRegistrationController, :create)
    get("/users/log_in", UserSessionController, :new)
    post("/users/log_in", UserSessionController, :create)
    get("/users/reset_password", UserResetPasswordController, :new)
    post("/users/reset_password", UserResetPasswordController, :create)
    get("/users/reset_password/:token", UserResetPasswordController, :edit)
    put("/users/reset_password/:token", UserResetPasswordController, :update)
  end

  scope "/", RasbetWeb do
    pipe_through([:browser, :require_authenticated_user])

    live("/users/settings", UserLive.Edit, :index)
    # get("/users/settings/confirm_email/:token", UserSettingsController, :confirm_email)

    live("/user/wallet", WalletLive.Index, :index)
    live("/user/wallet/top-up_d", WalletLive.Index, :topup_d)
    live("/user/wallet/top-up_w", WalletLive.Index, :topup_w)
    live("/user/bets", WalletLive.Bets, :index)
    live("/user/bets/completed", WalletLive.Bets, :completed)
  end

  scope "/admin", RasbetWeb do
    pipe_through([:browser, :require_admin_user])

    live("/users", UserLive.List, :index)
    live("/users/:id/edit", UserLive.Edit, :edit)
    live("/users/register", UserLive.Registration, :admin_new_user)
    post("/users/register", UserRegistrationController, :admin_create_user)

    live("/promos/create", PromosLive.Index, :create)
  end

  scope "/", RasbetWeb do
    pipe_through([:browser])

    delete("/users/log_out", UserSessionController, :delete)
    get("/users/confirm", UserConfirmationController, :new)
    post("/users/confirm", UserConfirmationController, :create)
    get("/users/confirm/:token", UserConfirmationController, :edit)
    post("/users/confirm/:token", UserConfirmationController, :update)
    get("/language/:locale", LanguageController, :update)
  end
end

lib/rasbet_web/controllers/user_registration_controller.ex
defmodule RasbetWeb.UserRegistrationController do
  use RasbetWeb, :controller

  alias Rasbet.Accounts
  alias Rasbet.Accounts.User
  alias RasbetWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/rasbet_web/views/user_registration_view.ex
defmodule RasbetWeb.UserRegistrationView do
  use RasbetWeb, :view
end

lib/rasbet_web/templates/user_registration/new.html.heex
<div class="flex flex-col place-content-center items-center">
  <h1 class="text-3xl mb-3"><%= gettext "Register"%></h1>
  <div class="bg-slate-200 px-4 py-4 rounded-2xl drop-shadow-md">
    <.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
      <%= if @changeset.action do %>
        <div class="alert alert-danger">
          <p><%= gettext "Oops, something went wrong! Please check the errors below."%></p>
        </div>
      <% end %>

      <.form_field
        type="email_input"
        form={f}
        field={:email}
        required={true}
        placeholder={gettext "Email"}
        label="Email"
      />

      <.form_field
        type="password_input"
        form={f}
        field={:password}
        placeholder="Password"
        label={gettext "Password"}
        required={true}
      />

      <.button label={gettext "Register"} color="primary" link_type="button" type="submit" class="w-full"/>
    </.form>

    <p>
      <%= link "Log in", to: Routes.user_session_path(@conn, :new) %> |
      <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
    </p>
  </div>
</div>